<?php

return [
'header' => 'Contacts',
'main-content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dignissim pretium ullamcorper. Fusce felis diam, porta non ultricies in, tempor ac odio. Vivamus rutrum magna id libero placerat lobortis. Ut ultrices lacinia tincidunt. Pellentesque sed mi eu orci malesuada molestie quis et elit. Pellentesque sapien velit, ultrices quis enim et, consectetur porttitor tellus. Praesent porta eget nunc sit amet dignissim. Nulla rhoncus ac massa et congue. Nam ut sem ante. In faucibus bibendum turpis, eget faucibus nulla eleifend sit amet. Praesent consequat nisl a sapien facilisis, eu condimentum tellus eleifend. Morbi vitae diam ex. Phasellus id porta turpis.

Etiam dictum nulla lectus, a interdum urna porta eu. Maecenas mollis ultricies justo, non eleifend lorem vulputate eget. Aenean a mattis augue. Donec odio turpis, maximus a arcu ultricies, condimentum placerat felis. Pellentesque ac libero non est ultrices aliquet nec quis elit. Aliquam bibendum viverra sollicitudin. Nunc dignissim dui in sodales volutpat. Phasellus posuere molestie turpis sit amet aliquet. Mauris egestas rutrum orci, eu maximus libero interdum vel. Sed id libero commodo justo varius suscipit in ac dolor. Phasellus et risus mi. Cras urna neque, suscipit non cursus vel, vestibulum at leo. Cras tristique tortor vitae rhoncus vestibulum. Phasellus tempus vel massa vel ornare. Maecenas commodo auctor erat egestas iaculis.

Duis finibus ex mi. Aenean diam magna, auctor nec sem vel, sagittis volutpat nibh. Curabitur vel quam pellentesque, vulputate dolor ultricies, finibus mauris. Pellentesque sollicitudin bibendum ipsum, id convallis risus condimentum ut. Aliquam odio eros, mattis ac vestibulum id, egestas et eros. Sed semper, orci eu placerat suscipit, neque enim accumsan ipsum, eget lacinia justo purus in lectus. Etiam blandit turpis eu sapien tempor ornare. Quisque a varius ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut pulvinar mi, eget venenatis neque. Morbi scelerisque pellentesque diam. Aliquam congue sollicitudin lectus, mattis interdum velit euismod eu.pull-left',
];